import db from '../config/database.js';

/**
 * Command Handler Service for workflow command nodes
 * Registers and executes Discord commands within workflow context
 */

/**
 * Register a command handler in the bot
 * @param {Object} bot - Bot configuration
 * @param {string} commandName - Command name
 * @param {Object} workflowNodes - Workflow nodes data
 * @returns {Promise<string>} Handler function code
 */
export async function registerCommandHandler(bot, commandName, workflowNodes) {
  // Find command-related nodes in workflow
  const commandNodes = workflowNodes.nodes.filter(node =>
    node.type === 'command-handler-suite' &&
    node.data.commandName === commandName
  );

  if (commandNodes.length === 0) {
    throw new Error('No command handler node found for this command');
  }

  // Get the workflow ID
  const workflowId = bot.workflow_id;

  // Build the handler function
  const handlerCode = `
// Command: ${commandName}
// Generated by DisFlow Platform
// Workflow ID: ${workflowId}

const { executeCommand } = require('./${commandName}Handler.js')(bot, workflowNodes);

module.exports = { executeCommand };
  `.trim();

  return handlerCode;
}

/**
 * Execute a command within workflow context
 * @param {Object} bot - Discord bot instance
 * @param {Object} workflowNodes - Workflow nodes data
 * @param {Object} interaction - Discord interaction event
 * @param {string} commandName - Command name
 */
export async function executeCommandHandler(bot, workflowNodes, interaction, commandName) {
  try {
    // Find command handler node for this command
    const commandNodes = workflowNodes.nodes.filter(node =>
      node.type === 'command-handler-suite' &&
      node.data.commandName === commandName
    );

    if (commandNodes.length === 0) {
      throw new Error(`No command handler configured for command: ${commandName}`);
    }

    // Get the workflow ID
    const workflowId = bot.workflow_id;

    // Build dynamic require for the handler file
    const handlerPath = `./${commandName}Handler.js`;

    // Require the handler module
    const handlerModule = require(handlerPath);

    // Check if handler exists and has execute function
    if (!handlerModule.executeCommand) {
      throw new Error(`Handler module for ${commandName} does not have executeCommand function`);
    }

    // Execute the command with workflow context
    await handlerModule.executeCommand(bot, workflowNodes, interaction);

    console.log(`[Workflow] Executed command: ${commandName} for bot ${bot.id}`);
  } catch (error) {
    console.error(`[Workflow] Error executing command ${commandName}:`, error);
    throw new Error(`Failed to execute command: ${error.message}`);
  }
}

/**
 * Get all command handlers from workflow
 * @param {Object} workflowNodes - Workflow nodes data
 * @returns {Array<Object>} Array of command handler nodes with their command names
 */
export function getCommandHandlers(workflowNodes) {
  return workflowNodes.nodes
    .filter(node => node.type === 'command-handler-suite')
    .map(node => ({
      id: node.id,
      commandName: node.data.commandName,
      config: node.data.config || {},
    }));
}
